### ISSUE TITLE
Add cpu benchmarks

### ISSUE THREAD

**Issue by johnrezzo** [hidden-refuge/bench-sh-2#1]
First of all, thanks for releasing this improved version of the original bench.sh script.
I was wondering if you could include some CPU benchmarks. I know that storage suffers the most from noisy neighbors, but it could be nice to have an idea of the vcpu(s) performance too.

**Comment by hidden-refuge** [comment]
I will see what I can do. The easiest would probably be to let the script fetch a copy of Geekbench, extract it and run it. Although this would fail it the server lacks some dependencies Geekbench might need. Especially 64 Bit operating systems could turn into a issue as they mostly lack required 32 bit libs that have to be installed afterwards.

**Comment by johnrezzo** [comment]
I can suggest: Prime95[1] and stress-ng[2][3].

The executable of Prime95 can be directly dropped into the machine just using `wget` and `tar zxfv` with no issues. I have tested it on FreeBSD 10.1-STABLE and Ubuntu 15.04. The only problem is getting rid of the initial menu and controlling how long the benchmarks must run. These are the outputs contained in my "results.txt" files:

```
# FreeBSD 10.1-STABLE bare-metal machine

AMD Phenom(tm) II X6 1090T Processor
CPU speed: 3205.16 MHz, 6 cores
CPU features: 3DNow!, SSE, SSE2
L1 cache size: 64 KB
L2 cache size: 512 KB, L3 cache size: 6 MB
L1 cache line size: 64 bytes
L2 cache line size: 64 bytes
L1 TLBS: 48
L2 TLBS: 512
Prime95 64-bit version 28.5, RdtscTiming=1
Best time for 1024K FFT length: 15.236 ms., avg: 16.036 ms.
Best time for 1280K FFT length: 19.598 ms., avg: 20.034 ms.
Best time for 1536K FFT length: 24.254 ms., avg: 27.197 ms.
Best time for 1792K FFT length: 29.356 ms., avg: 31.540 ms.
Best time for 2048K FFT length: 32.409 ms., avg: 33.824 ms.
Best time for 2560K FFT length: 41.730 ms., avg: 42.930 ms.
```
```
# Vultr VPS running Ubuntu 15.04 (3.19.0-28-generic)

Virtual CPU e7da7129d3ee
CPU speed: 2400.04 MHz
CPU features: Prefetch, SSE, SSE2, SSE4, AVX, AVX2, FMA
L1 cache size: 32 KB
L2 cache size: 2 MB
L1 cache line size: 64 bytes
L2 cache line size: 64 bytes
Prime95 64-bit version 28.5, RdtscTiming=1
Best time for 1024K FFT length: 5.853 ms., avg: 6.317 ms.
Best time for 1280K FFT length: 7.628 ms., avg: 7.805 ms.
Best time for 1536K FFT length: 9.258 ms., avg: 9.516 ms.
Best time for 1792K FFT length: 11.157 ms., avg: 11.617 ms.
Best time for 2048K FFT length: 12.893 ms., avg: 13.186 ms.
Best time for 2560K FFT length: 16.423 ms., avg: 16.549 ms.
Best time for 3072K FFT length: 19.950 ms., avg: 20.079 ms.
Best time for 3584K FFT length: 23.930 ms., avg: 24.263 ms.
Best time for 4096K FFT length: 27.022 ms., avg: 27.178 ms.
Best time for 5120K FFT length: 34.670 ms., avg: 35.372 ms.
Best time for 6144K FFT length: 42.107 ms., avg: 44.509 ms.
Best time for 7168K FFT length: 50.112 ms., avg: 51.730 ms.
```
stress-ng seems to be a better fit for the job. It comes as deb package and as FreeBSD port, too. I haven't tested it out, though.

[1] http://www.mersenne.org/download/
[2] http://www.cyberciti.biz/faq/stress-test-linux-unix-server-with-stress-ng/
[3] http://www.ubuntugeek.com/stress-ng-tool-to-load-and-stress-your-ubuntu-system.html

**Comment by hidden-refuge** [comment]
Thanks for the links and explanation. I'll get some VMs up and running to see which solution might be the best.

**Comment by johnrezzo** [comment]
No problem. Forgot to mention [UNIX Bench](https://github.com/kdlucas/byte-unixbench) ([example output](http://serverbear.com/benchmark/2014/11/26/DzOLHnikmMP7sHVB)), but last update (v5.1.2) was released more than 5 years ago.

**Comment by hidden-refuge** [comment]
So I've tried mprime (Prime95) on a Linux machine. It would basically work if the menu thing wouldn't be so annoying. Beside that, the problem with prime95 is also that the user has to choose the amount of threads and stress tests and etc.. An automation seems a bit hard here. User interaction is necessary here (which I basically want to avoid as the script should just make a test run and present the results). Atleast it just ran after extracting it without complaining about any dependencies.

stress/stress-ng needs to be installed or if not available in packages it needs to be compiled. On most servers I guess this would require to install building tools and tons of dependencies. So I didn't even bother to try it out. It would be too much of a hassle to write workarounds for every possible Linux distribution and the package managers to download everything required.

Unix Bench always has some missing dependencies on me. Mostly the Time-HiRes perl module. Again I'd have to write code to figure out the OS and figure out it's package manager, package name and install the missing dependencies. Too much work for this script which is meant to be just as simple as possible and only using things that really exist on literally any Linux distribution (cat, wget, awk, grep, files with OS information, CPU, RAM and etc...).

I honestly don't have the time and mood to work on getting this whole OS detection thing together and then have it figure out the package manager and package names for dependencies. I think you know how much work that is for several OSs. I know most always use Debian/Ubuntu or CentOS but still this is meant to cover almost any Linux distribution.

Going to see how Geekbench performs on any minimal distribution. Usually it works without any complaints about missing things. That's only usually though. I remember running it on a 64 Bit distribution not so long ago and just didn't work unless I installed some 32 bit libs.

A lot of people wish to have a benchmark for CPU in this kind of scripts but it's hard to implement due to the factors that I mentioned before and may even more other reasons.

**Comment by johnrezzo** [comment]
ServerBear uses a bash script to check for the required dependencies.

Take a look at `sb.sh` in their repository:
https://github.com/Crowd9/Benchmark

**Comment by hidden-refuge** [comment]
I added Geekbench for the system benchmark. Currently testing it. So it's kinda experimental.

./bench -b will perform the normal test with sysinfo, speedtest over IPv4, IO test and the benchmark. 
./bench -b6 will perform the normal test but with IPv6 only for the speedtest, so sysinfo, speedtest over IPv6, IO test and the benchmark
./bench -b46 runs both speedtests, so sysinfo, IPv4 and IPv6 speedtest, IO test and the benchmark

The benchmark has a note about possible failure due to possible lack of dependencies and such. Output is redirected to a file called "results.txt" in $HOME of the user that runs the script.
